### ISSUE TITLE
Error when installing code2inv-fe

### ISSUE THREAD

**Issue by ireneGP** [PL-ML/code2inv#3]
Hello,

I am trying to install `code2inv-fe` after successfully installed the latest version of `sparrow`. But somehow when running `make` in the `code2inv-fe` folder, I got the following error msg:

````
➜  code2inv-fe git:(master) ✗ make
ocaml setup.ml -build
Finished, 0 targets (0 cached) in 00:00:00.
+ /home/irenegp/.opam/sparrow-4.06.1+flambda/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -thread -
package apron -package apron.octMPQ -package batteries -package cil -package lymp -package ocamlgraph
-package ppx_compare -package yojson -I src/util -I src/core -I src/instance -I src/semantics -I src/s
parse -I src/program -I src/domain -I src/report -I src/strategy -o src/util/vocab.cmx src/util/vocab.
ml
File "src/util/vocab.ml", line 1:
Error: The implementation src/util/vocab.ml
       does not match the interface src/util/vocab.cmi:
       Values do not match:
         val link_by_sep : string -> string -> string -> string
       is not included in
         val link_by_sep : bytes -> bytes -> bytes -> bytes
       File "src/util/vocab.mli", line 35, characters 0-50:
         Expected declaration
       File "src/util/vocab.ml", line 61, characters 4-15: Actual declaration
Command exited with code 2.
Compilation unsuccessful after building 37 targets (0 cached) in 00:00:09.
E: Failure("Command ''/home/ireneGP/.opam/sparrow-4.06.1+flambda/bin/ocamlbuild' src/core/main.native
 src/core/vis.native -tag debug' terminated with error code 10")
Makefile:9: recipe for target 'build' failed
````

Could anyone shed some lights on what's going on here? Or at least let me know what's the exact version of `sparrow` and `ocaml` tool chain? Thanks.

**Comment by ireneGP** [comment]
@XujieSi  @mayurnaik  Hello, could you shed some lights on this issue? It seems to me some configurations are not correct, but not sure what's going on actually. Thanks a lot!

**Comment by XujieSi** [comment]
@ireneGP Very glad to learn you are interested in our work. 
Can you build the [Sparrow](https://github.com/ropas/sparrow) (according to their instructions) successfully? Our tool is based on Sparrow and has the same configuration.

**Comment by ireneGP** [comment]
Thank you for looking into this. Yes, I can build their tool. But then I was trapped by the above msg when executing make.

Indeed I tried to build from their girhub version, and also use opam to install, but none of them work for me.

**Comment by ireneGP** [comment]
It seems like a version inconsistency, could you confirm this? Thank you!

**Comment by XujieSi** [comment]
@ireneGP The version of OCaml we used is "4.04.0" 
Let me know if this does not work or you get other issues

**Comment by ireneGP** [comment]
@XujieSi @aadityanaik  Thank you a lot for the support. I am able to somehow using the following way to install the tool:

    opam switch 4.04.0
    eval `opam config env`
    opam install sparrow
    opam install base core
    make
